import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

export const translations = {
  en: {
    brand:        '🔧 Smart Mechanic Finder',
    myRequests:   '📋 My Requests',
    findMechanics:'🔍 Find Mechanics',
    logout:       'Logout',
    heroTitle:    'Smart Mechanic Finder',
    heroSub:      'Find the best nearby mechanic using AI ranking.',
    detectingLocation: 'Detecting your location…',
    locationDetected:  'Location detected.',
    locationDenied:    'Location access denied. Click the map or enter coordinates.',
    locationUnavail:   'Location unavailable.',
    locationTimeout:   'Timed out.',
    locationFailed:    'Could not get location.',
    locationNotSet:    'Please set your location first.',
    problemRequired:   'Please enter a car problem.',
    coordsInvalid:     'Enter valid coordinates.',
    findingMechanics:  'Finding the best mechanics…',
    foundResults:      (n, district, radius) => `Found ${n} recommendations${district ? ` in ${district}` : ''} within ${radius} km.`,
    locationHint: 'Use GPS, click the map, or enter coordinates manually.',
    useMyLocation:'📍 Use My Location',
    hideManual:   'Hide manual entry',
    enterManual:  'Enter coordinates manually',
    latitude:     'Latitude',
    longitude:    'Longitude',
    apply:        '✔ Apply',
    clearLocation:'✕ Clear',
    carProblem:   'Car Problem',
    carProblemPh: 'e.g. Brake System, Oil Change',
    urgency:      'Urgency',
    normal:       'Normal',
    urgent:       'Urgent',
    emergency:    'Emergency',
    findBtn:      '🔍 Find Mechanics',
    topRecs:      'Top Recommendations',
    noResults:    'Search for mechanics to see results here.',
    distance:     'Distance',
    rating:       'Rating',
    open24:       'Open 24/7',
    yes:          '✅ Yes',
    no:           'No',
    suitability:  'Suitability',
    showOnMap:    '🗺️ Show on Map',
    requestService:'🚗 Request Service',
    mapView:      'Map View',
    you:          'You',
    bestMatch:    'Best Match',
    others:       'Others',
    activeRequests: '📋 Your Active Requests',
    clearAll:     '✕ Clear all',
    pending:      (g) => `⏳ Request sent — waiting for ${g} to respond…`,
    accepted:     (g) => `✅ ${g} accepted your request! They are on their way or will contact you shortly.`,
    declined:     (g) => `❌ ${g} is currently not available. Please try another garage.`,
    completed:    (g) => `🏁 Service completed by ${g}!`,
    rateBtn:      '⭐ Rate Your Experience',
    thankRating:  '✅ Thank you for your rating!',
    requestHistory: '📋 My Request History',
    totalRequests:  (n) => `All your service requests — ${n} total`,
    liveUpdating:   '🟢 Live — auto-updating',
    refresh:        '🔄 Refresh',
    noRequestsAll:  'No requests yet.',
    noRequestsFilter: (f) => `No ${f} requests.`,
    findMechanicBtn:'🔍 Find a Mechanic',
    rateService:    '⭐ Rate This Service',
    viewLocation:   '📍 View My Location',
    yourRating:     'Your rating',
    createAccount:  '📝 Create Account',
    registerSub:    'Register to send service requests and track them in real time.',
    fullName:       'Full Name',
    fullNamePh:     'e.g. Jean Pierre',
    phoneNumber:    'Phone Number',
    phonePh:        'e.g. 0785 761 688',
    emailAddr:      'Email Address',
    emailOptional:  '(optional — for email notifications)',
    emailPh:        'e.g. jean@example.com',
    password:       'Password',
    passwordPh:     'At least 6 characters',
    confirmPass:    'Confirm Password',
    confirmPassPh:  'Repeat your password',
    createBtn:      '✅ Create Account',
    creating:       'Creating…',
    alreadyAccount: 'Already have an account?',
    loginHere:      'Login here',
    areYouGarage:   'Are you a garage?',
    registerGarage: 'Register your garage',
    loginTitle:     '🔑 Welcome Back',
    loginSub:       'Sign in to your account.',
    loginBtn:       '🔓 Login',
    loggingIn:      'Signing in…',
    noAccount:      "Don't have an account?",
    registerHere:   'Register here',
    registerGarageTitle: '🔧 Register Your Garage',
    registerGarageSub:   'Select your garage to create a dashboard account.',
    pendingNotice:  '⚠️ After registration, an admin will verify your account before you can log in.',
    searchGarage:   'Search Your Garage',
    searchGaragePh: 'Type garage name to search…',
    yourPhone:      'Your Phone Number',
    submitReg:      '📤 Submit Registration',
    submitting:     'Submitting…',
    regSuccess:     '✅ Registration Submitted!',
    regSuccessSub:  'An admin will review your account within 24 hours. You will be able to log in once verified.',
    goToLogin:      '→ Go to garage login',
    alreadyReg:     'Already registered?',
    loginDashboard: 'Login to dashboard',
    liveRefresh:    'Live — refreshes every 10 seconds',
    pendingLabel:   'Pending',
    noRequestsYet:  'No requests yet.',
    getDirections:  '🚗 Get Directions',
    customerLoc:    '📍 Customer Location',
    accept:         '✅ Accept',
    decline:        '❌ Decline',
    markComplete:   '🏁 Mark Completed',
    waitingRating:  '⏳ Waiting for user rating…',
    userRated:      'User rated',
    loadingDir:     '⏳ Loading…',
    navigateGM:     '🚗 Navigate in Google Maps',
    straightLine:   'straight line',
    yourGarage:     'your garage',
    customer:       'Customer',
  },

  rw: {
    brand:        '🔧 Smart Mechanic Finder',
    myRequests:   '📋 Ubusabe Bwanjye',
    findMechanics:'🔍 Shaka Garage',
    logout:       'Gusohoka',
    heroTitle:    'Smart Mechanic Finder',
    heroSub:      'Shaka garage nziza ikwegereye hifashishijwe ubwenge buhangano (AI).',
    detectingLocation: 'Birashakwa aho uri…',
    locationDetected:  'Aho uri barasanze.',
    locationDenied:    'Ntabwo wemeye GPS. Kanda ku ikarita cyangwa wandike coordinates.',
    locationUnavail:   'Aho uri ntibashobora kubisanga.',
    locationTimeout:   'Igihe kirangiye.',
    locationFailed:    'Ntibashobora kubona aho uri.',
    locationNotSet:    'Banza ushyireho aho uri.',
    problemRequired:   "Injiza ikibazo cy'imodoka.",
    coordsInvalid:     'Injiza coordinates zikwiye.',
    findingMechanics:  'Gushaka garage nziza…',
    foundResults:      (n, district, radius) => `Habonetse garage ${n} muri ${district || ''} mu ntera ya km ${radius}.`,
    locationHint: 'Koresha GPS, kanda ku ikarita cyangwa wandike coordinates ukoresheje intoki.',
    useMyLocation:'📍 Koresha Ahantu Ngeze',
    hideManual:   'Hisha andika coordinates',
    enterManual:  'Andika coordinates ukoresheje intoki',
    latitude:     'Latitude',
    longitude:    'Longitude',
    apply:        '✔ Injiza',
    clearLocation:'✕ Siba',
    carProblem:   "Ikibazo cy'Imodoka",
    carProblemPh: 'urugero: Gusana rusange, Amavuta',
    urgency:      'Ubwihutirwe',
    normal:       'Bisanzwe',
    urgent:       'Byihutirwa',
    emergency:    'Urgence',
    findBtn:      '🔍 Shaka Garage',
    topRecs:      'Garage Zisabwa Cyane',
    noResults:    'Shaka garage kugira ngo ubone ibisubizo.',
    distance:     'Intera',
    rating:       'Amanota',
    open24:       'Bafungura 24/7',
    yes:          '✅ Yego',
    no:           'Oya',
    suitability:  'Guhuza',
    showOnMap:    '🗺️ Erekana ku Ikarita',
    requestService:'🚗 Saba Serivisi',
    mapView:      'Ikarita',
    you:          'Wewe',
    bestMatch:    'Uwo Batoranijwe',
    others:       'Abandi',
    activeRequests: '📋 Ubusabe Bwawe Bukorwa',
    clearAll:     '✕ Siba byose',
    pending:      (g) => `⏳ Ubusabe bwoherejwe — gutegereza ${g} gusubiza…`,
    accepted:     (g) => `✅ ${g} yemeye ubusabe bwawe! Baza kugera cyangwa bazakuvugisha vuba.`,
    declined:     (g) => `❌ ${g} ntabwo abasha ubu. Gerageza undi garage.`,
    completed:    (g) => `🏁 Serivisi irarangiye kuri ${g}!`,
    rateBtn:      '⭐ Tanga Amanota',
    thankRating:  '✅ Urakoze amanota yawe!',
    requestHistory: "📋 Amateka y'Ubusabe Bwanjye",
    totalRequests:  (n) => `Ubusabe bwawe bwose — ${n} hamwe`,
    liveUpdating:   '🟢 Birakora — biravugurura',
    refresh:        '🔄 Vugurura',
    noRequestsAll:  'Nta busabe buhari.',
    noRequestsFilter: (f) => `Nta busabe bwa ${f}.`,
    findMechanicBtn:'🔍 Shaka Garage',
    rateService:    '⭐ Tanga Amanota',
    viewLocation:   '📍 Reba Aho Ndi',
    yourRating:     'Amanota yawe',
    createAccount:  '📝 Fungura Konti',
    registerSub:    'Iyandikishe kohereza ubusabe no kubureba igihe cyose.',
    fullName:       'Amazina Yose',
    fullNamePh:     'urugero: Jean Pierre',
    phoneNumber:    'Numero ya Telefoni',
    phonePh:        'urugero: 0785 761 688',
    emailAddr:      'Imeyili',
    emailOptional:  '(si ngombwa — kugira ngo ubone amakuru)',
    emailPh:        'urugero: jean@example.com',
    password:       'Ijambo Banga',
    passwordPh:     'Nibura inyuguti 6',
    confirmPass:    'Emeza Ijambo Banga',
    confirmPassPh:  'Subiramo ijambo banga',
    createBtn:      '✅ Fungura Konti',
    creating:       'Birakozwe…',
    alreadyAccount: 'Usanzwe ufite konti?',
    loginHere:      'Injira hano',
    areYouGarage:   'Uri garage?',
    registerGarage: 'Iyandikishe garage yawe',
    loginTitle:     '🔑 Murakaza Neza',
    loginSub:       'Injira muri konti yawe.',
    loginBtn:       '🔓 Injira',
    loggingIn:      'Birinjira…',
    noAccount:      'Nta konti ufite?',
    registerHere:   'Iyandikishe hano',
    registerGarageTitle: '🔧 Iyandikishe Garage Yawe',
    registerGarageSub:   'Hitamo garage yawe kugira ngo ufungure konti.',
    pendingNotice:  '⚠️ Nyuma yo kwiyandikisha, admin azasuzuma konti yawe mbere yo kwinjira.',
    searchGarage:   'Shaka Garage Yawe',
    searchGaragePh: 'Andika izina rya garage…',
    yourPhone:      'Numero Yawe ya Telefoni',
    submitReg:      '📤 Ohereza Kwiyandikisha',
    submitting:     'Biratumwa…',
    regSuccess:     '✅ Kwiyandikisha Byoherejwe!',
    regSuccessSub:  'Admin azasuzuma konti yawe mu masaha 24. Uzashobora kwinjira nyuma yo kwemezwa.',
    goToLogin:      '→ Jya kwinjira kwa garage',
    alreadyReg:     'Usanzwe wiyandikishije?',
    loginDashboard: 'Injira mu dashboard',
    liveRefresh:    'Birakora — biravugurura buri masegonda 10',
    pendingLabel:   'Bitegereje',
    noRequestsYet:  'Nta busabe buhari.',
    getDirections:  '🚗 Reba Inzira',
    customerLoc:    '📍 Aho Umukiriya Ari',
    accept:         '✅ Emera',
    decline:        '❌ Anga',
    markComplete:   '🏁 Rangiza Serivisi',
    waitingRating:  "⏳ Gutegereza amanota y'umukiriya…",
    userRated:      'Umukiriya yatanze amanota',
    loadingDir:     '⏳ Birategerezwa…',
    navigateGM:     '🚗 Fungura muri Google Maps',
    straightLine:   'murongo utunganye',
    yourGarage:     'garage yawe',
    customer:       'Umukiriya',
  }
}

export const specialityTranslations = {
  'Engine Repair':          'Gusana moteri',
  'Brake System':           'Gusana sisitemu ya feri',
  'Electrical Systems':     'Gusana ibice by\'amashanyarazi',
  'Transmission Repair':    'Gusana gearbox / sisitemu y\'ikwirakwizwa ry\'imbaraga',
  'Suspension & Steering':  'Gusana suspension n\'icyerekezо',
  'Diagnostic Scanning':    'Gusuzuma ibibazo hifashishijwe ikoranabuhanga',
  'Oil Change':             'Guhindura amavuta',
  'Tire & Wheel':           'Gusana amapine n\'ibiziga',
  'Air Conditioning':       'Gusana climatiseur y\'imodoka',
  'Bodywork':               'Gusana umubiri w\'imodoka',
  'Welding':                'Gusudira',
  'Exhaust System':         'Gusana sisitemu isohora imyuka',
  'General Repair':         'Gusana rusange',
}

export function getSpecialityLabel(name, lang) {
  if (lang !== 'rw' || !name) return name
  // Exact match first
  if (specialityTranslations[name]) return specialityTranslations[name]
  // Case-insensitive match
  const lower = name.toLowerCase()
  for (const [key, val] of Object.entries(specialityTranslations)) {
    if (key.toLowerCase() === lower) return val
  }
  // Partial match — if the stored value contains a known key word
  for (const [key, val] of Object.entries(specialityTranslations)) {
    if (lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)) return val
  }
  return name
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() =>
    localStorage.getItem('smf_lang') || 'en'
  )

  function toggleLang() {
    const next = lang === 'en' ? 'rw' : 'en'
    setLang(next)
    localStorage.setItem('smf_lang', next)
  }

  const t = translations[lang]

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
